spring:
  # Datasource config
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: ghjljk;fq

  # Hibernate properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

  # Work with PUT/PATCH/DELETE methods from forms
  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  servlet:
    context-path: /library